services:
  inventory-atk:
    container_name: inventory-atk
    build: 
      context: .
    restart: always
    # Mengambil semua variabel dari file .env (DATABASE_URL, dll)
    env_file:
      - .env
    networks:
      - tunnel-network

networks:
  tunnel-network:
    external: true